"""The campground catalog (§8k) — the known universe, not a search-hit list.

The rule this module exists to enforce: **the catalog never silently shrinks.**
A campground that a live enumeration drops is kept and flagged, because the
worst failure this app can have is a bookable place you can't see (the Reehers
Camp Horse Camp case).

Three cadences:
  1. seed   — `data/seed/pnw_campgrounds.json`, committed, the completeness floor
  2. refresh— live enumeration on a slow cadence, diffed against the floor
  3. scan   — availability, continuous, handled by scanner.py
"""

from __future__ import annotations

import gzip
import json
import logging
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

from . import db, store
from .config import Config, Source
from .providers import build_provider
from .providers.base import STATUS_STALE, STATUS_UNKNOWN, Campground, Provider

log = logging.getLogger(__name__)

#: Repo-anchored for the same reason as DEFAULT_DB_PATH: a missing seed file
#: loads as an empty catalog, so a cwd-relative default turned "run from the
#: wrong directory" into a silent zero-campground map.
DEFAULT_SEED_PATH = db.REPO_ROOT / "data" / "seed" / "pnw_campgrounds.json"
#: Per-site inventory, committed alongside the campground seed. It exists
#: because measuring it costs hundreds of paced requests and the answer changes
#: on the order of years — keeping it only in somebody's local database would
#: mean re-fetching it on every fresh checkout.
DEFAULT_CAMPSITE_SEED_PATH = db.REPO_ROOT / "data" / "seed" / "campsites.json.gz"

#: Fields worth committing. The raw `attributes` blob is deliberately left out:
#: it is large, mostly redundant with the normalized columns, and re-derivable.
CAMPSITE_SEED_FIELDS = (
    "provider", "campground_id", "site_id", "name", "loop", "site_type",
    "type_of_use", "reservable", "max_vehicle_length", "site_access",
    "access_class", "driveway_entry", "max_people", "accessible",
    "latitude", "longitude", "source",
)


# --------------------------------------------------------------------------
# seed
# --------------------------------------------------------------------------

def load_seed(path: str | Path | None = None) -> list[Campground]:
    path = Path(path or DEFAULT_SEED_PATH)
    if not path.exists():
        return []
    data = json.loads(path.read_text())
    entries = data.get("campgrounds", data) if isinstance(data, dict) else data
    return [
        Campground(
            provider=e["provider"],
            id=str(e["id"]),
            name=e["name"],
            rec_area=e.get("rec_area"),
            state=e.get("state"),
            latitude=e.get("latitude"),
            longitude=e.get("longitude"),
            reservation_type=e.get("reservation_type", "reservable"),
            status=e.get("status", STATUS_UNKNOWN),
            status_reason=e.get("status_reason"),
            coord_source=e.get("coord_source"),
            first_come_sites=e.get("first_come_sites"),
            sites_total=e.get("sites_total"),
            sites_not_bookable=e.get("sites_not_bookable"),
            length_data_quality=e.get("length_data_quality"),
        )
        for e in entries
    ]


def seed_catalog(
    conn: sqlite3.Connection,
    seed: Optional[Iterable[Campground]] = None,
    path: str | Path | None = None,
    now: Optional[datetime] = None,
) -> tuple[int, int]:
    """Load the committed seed into `campgrounds`. Idempotent."""
    campgrounds = list(seed) if seed is not None else load_seed(path)
    return store.upsert_campgrounds(conn, campgrounds, seeded=True, now=now)


def write_seed(
    campgrounds: Iterable[Campground],
    path: str | Path | None = None,
    note: str = "",
) -> Path:
    """Serialize an enumeration to the committed seed file.

    This is the "run the scraper once and commit the result" path (§8k) —
    `manage.py catalog-refresh --write-seed`.
    """
    path = Path(path or DEFAULT_SEED_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    campgrounds = list(campgrounds)
    payload = {
        "_meta": {
            "note": note or "Generated by manage.py catalog-refresh --write-seed",
            "count": len(campgrounds),
        },
        "campgrounds": [
            {
                "provider": c.provider, "id": c.id, "name": c.name,
                "rec_area": c.rec_area, "state": c.state,
                "latitude": c.latitude, "longitude": c.longitude,
                "reservation_type": c.reservation_type,
                # Kept in the committed seed so the provenance of a coordinate
                # survives a database rebuild — otherwise the claim is only as
                # durable as someone's local .db file.
                "coord_source": c.coord_source,
                "first_come_sites": c.first_come_sites,
                # Measured once and committed: site inventory changes on the
                # order of years, so this must survive a database rebuild
                # rather than being re-fetched.
                "sites_total": c.sites_total,
                "sites_not_bookable": c.sites_not_bookable,
                "length_data_quality": c.length_data_quality,
            }
            for c in sorted(campgrounds, key=lambda c: (c.provider, c.id))
        ],
    }
    path.write_text(json.dumps(payload, indent=2) + "\n")
    return path


# --------------------------------------------------------------------------
# live enumeration + diff
# --------------------------------------------------------------------------

@dataclass
class RefreshReport:
    added: int = 0
    updated: int = 0
    missing_from_live: list[Campground] = field(default_factory=list)
    provider_errors: dict[str, str] = field(default_factory=dict)
    enumerated: int = 0

    @property
    def ok(self) -> bool:
        return not self.provider_errors

    def summary(self) -> str:
        parts = [
            f"enumerated={self.enumerated}",
            f"added={self.added}",
            f"updated={self.updated}",
            f"kept-but-missing={len(self.missing_from_live)}",
        ]
        if self.provider_errors:
            parts.append(f"errors={len(self.provider_errors)}")
        return " ".join(parts)


def enumerate_live(
    sources: Iterable[Source],
    report: Optional[RefreshReport] = None,
    provider_factory=build_provider,
) -> list[Campground]:
    """Enumerate every configured source's full directory.

    A provider that raises is recorded and skipped — its catalog entries then
    fall through to the "missing from live" path below and are KEPT as stale,
    never deleted. A source outage must not empty the map.
    """
    report = report or RefreshReport()
    found: list[Campground] = []
    for source in sources:
        try:
            provider: Provider = provider_factory(source.provider, state=source.state)
            cgs = provider.list_campgrounds(
                state=source.state, rec_area_ids=source.rec_area_ids
            )
        except Exception as exc:  # noqa: BLE001 - one bad source must not kill the refresh
            log.warning("enumeration failed for %s: %s", source.label, exc)
            report.provider_errors[source.label] = str(exc)
            continue
        for cg in cgs:
            if cg.state is None:
                cg.state = source.state
        found.extend(cgs)
    report.enumerated = len(found)
    return found


def refresh_catalog(
    conn: sqlite3.Connection,
    sources: Iterable[Source],
    provider_factory=build_provider,
    now: Optional[datetime] = None,
) -> RefreshReport:
    """Enumerate live, diff against the stored catalog, never shrink (§8k)."""
    report = RefreshReport()
    live = enumerate_live(sources, report, provider_factory)

    before = {cg.key: cg for cg in store.list_campgrounds(conn)}
    added, updated = store.upsert_campgrounds(conn, live, seeded=False, now=now)
    report.added, report.updated = added, updated

    live_keys = {cg.key for cg in live}
    scoped_providers = set()
    for source in sources:
        if source.label not in report.provider_errors:
            scoped_providers.add(build_provider_name(source.provider))

    for key, cg in before.items():
        if key in live_keys:
            continue
        # Only judge providers we actually enumerated successfully this run.
        if cg.provider not in scoped_providers:
            continue
        # Present in our catalog, absent from a successful live enumeration.
        # This is the Reehers signature: keep it, flag it, never drop it.
        report.missing_from_live.append(cg)
        store.set_campground_status(
            conn,
            cg.provider,
            cg.id,
            STATUS_STALE if cg.status != STATUS_UNKNOWN else STATUS_UNKNOWN,
            "present in catalog but absent from the latest live enumeration "
            "— kept as a completeness floor (§8k)",
            now=now,
        )
    return report


def build_provider_name(spec: str) -> str:
    """The provider `name` a spec resolves to, without instantiating it.

    The instance suffix has to survive: `ReserveAmerica:OR` names itself
    `ReserveAmerica:OR`, not `ReserveAmerica`. Dropping it made
    `scoped_providers` below never match a ReserveAmerica catalog row, which
    quietly disabled the "present in catalog, absent from live" check — the
    §8k safety net — for the one provider that exists because of it.
    """
    family, _, instance = spec.partition(":")
    if family in ("Mock", "MockProvider"):
        return "Mock"
    if family.startswith("Search"):
        family = family[len("Search"):]
    return f"{family}:{instance}" if instance else family


def catalog_refresh(
    conn: sqlite3.Connection,
    config: Config,
    seed_path: str | Path | None = None,
    now: Optional[datetime] = None,
) -> RefreshReport:
    """Full catalog pass: seed floor first, then live diff on top."""
    seed_catalog(conn, path=seed_path, now=now)
    # The per-site inventory rides along: it cost hundreds of paced requests to
    # measure and changes on the order of years, so a fresh database loads it
    # rather than re-fetching it.
    seed_campsites(conn, now=now)
    return refresh_catalog(conn, config.sources, now=now)


# --------------------------------------------------------------------------
# per-site inventory seed
# --------------------------------------------------------------------------

def write_campsite_seed(
    rows: Iterable[dict],
    path: str | Path | None = None,
    note: str = "",
) -> Path:
    """Commit the per-site inventory so a rebuild doesn't re-fetch it."""
    path = Path(path or DEFAULT_CAMPSITE_SEED_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = list(rows)
    payload = {
        "_meta": {
            "note": note or "Generated by manage.py backfill-site-inventory",
            "count": len(rows),
        },
        "campsites": [
            {k: r.get(k) for k in CAMPSITE_SEED_FIELDS}
            for r in sorted(rows, key=lambda r: (r.get("provider") or "",
                                                 r.get("campground_id") or "",
                                                 str(r.get("site_id") or "")))
        ],
    }
    # Gzipped, and written compactly. Pretty-printed this file was 3.2 MB —
    # larger than the entire repository's history — and every regeneration
    # would add another copy that git cannot store as a small difference.
    # Compressed it is about 130 KB for the same 6,822 rows.
    body = json.dumps(payload, separators=(",", ":")).encode()
    with gzip.open(path, "wb") as fh:
        fh.write(body)
    return path


def load_campsite_seed(path: str | Path | None = None) -> list[dict]:
    """Read the per-site seed. Accepts the gzipped file or a plain one."""
    path = Path(path or DEFAULT_CAMPSITE_SEED_PATH)
    if not path.exists():
        # Tolerate an uncompressed file beside it, so an older checkout or a
        # hand-made copy still loads.
        plain = path.with_suffix("") if path.suffix == ".gz" else None
        if plain and plain.exists():
            path = plain
        else:
            return []
    if path.suffix == ".gz":
        with gzip.open(path, "rb") as fh:
            data = json.loads(fh.read().decode())
    else:
        data = json.loads(path.read_text())
    return data.get("campsites", data) if isinstance(data, dict) else data


def seed_campsites(
    conn: sqlite3.Connection,
    path: str | Path | None = None,
    now: Optional[datetime] = None,
) -> int:
    """Load the committed per-site inventory. Idempotent."""
    total = 0
    by_campground: dict = {}
    for row in load_campsite_seed(path):
        key = (row.get("provider"), row.get("campground_id"))
        by_campground.setdefault(key, []).append(row)
    for (provider, campground_id), rows in by_campground.items():
        total += store.upsert_campsites(
            conn, provider, campground_id, rows,
            source=rows[0].get("source") or "committed seed", now=now,
        )
    return total
